INFO : Watching for file changes with StatReloader
DEBUG : not loged in
ERROR : Internal Server Error: /users/
Traceback (most recent call last):
  File "/home/amin/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: flights_flight.cost

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/amin/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/projects/github/amcsui/amcsui/users/views.py", line 16, in index
    return index_view(request)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/amin/projects/github/amcsui/amcsui/users/helpers.py", line 21, in index_view
    return render(request, "users/index.html", {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/test/utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/test/utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/template/defaulttags.py", line 194, in render
    len_values = len(values)
                 ^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/db/models/query.py", line 376, in __len__
    self._fetch_all()
  File "/home/amin/.local/lib/python3.11/site-packages/django/db/models/query.py", line 1867, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/db/models/query.py", line 87, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1398, in execute_sql
    cursor.execute(sql, params)
  File "/home/amin/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/home/amin/.local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/amin/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: flights_flight.cost
DEBUG : not loged in
DEBUG : not loged in
DEBUG : not loged in
ERROR : Internal Server Error: /users/
Traceback (most recent call last):
  File "/home/amin/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: flights_flight.capacity

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/amin/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/projects/github/amcsui/amcsui/users/views.py", line 16, in index
    return index_view(request)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/amin/projects/github/amcsui/amcsui/users/helpers.py", line 21, in index_view
    return render(request, "users/index.html", {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/test/utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/test/utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/template/defaulttags.py", line 194, in render
    len_values = len(values)
                 ^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/db/models/query.py", line 376, in __len__
    self._fetch_all()
  File "/home/amin/.local/lib/python3.11/site-packages/django/db/models/query.py", line 1867, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/db/models/query.py", line 87, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1398, in execute_sql
    cursor.execute(sql, params)
  File "/home/amin/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/home/amin/.local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/amin/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: flights_flight.capacity
DEBUG : not loged in
DEBUG : not loged in
DEBUG : not loged in
DEBUG : not loged in
DEBUG : not loged in
DEBUG : not loged in
DEBUG : not loged in
DEBUG : not loged in
DEBUG : not loged in
DEBUG : not loged in
INFO : Watching for file changes with StatReloader
INFO : Watching for file changes with StatReloader
INFO : /home/amin/projects/github/amcsui/amcsui/products/urls.py changed, reloading.
INFO : Watching for file changes with StatReloader
INFO : Watching for file changes with StatReloader
WARNING : Not Found: /
ERROR : Internal Server Error: /products/
Traceback (most recent call last):
  File "/home/amin/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: products_product

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/amin/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/projects/github/amcsui/amcsui/products/views.py", line 6, in index
    return render(request, "products/index.html",{"products":products})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/template/defaulttags.py", line 194, in render
    len_values = len(values)
                 ^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/db/models/query.py", line 376, in __len__
    self._fetch_all()
  File "/home/amin/.local/lib/python3.11/site-packages/django/db/models/query.py", line 1867, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/db/models/query.py", line 87, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1398, in execute_sql
    cursor.execute(sql, params)
  File "/home/amin/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/home/amin/.local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/amin/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: products_product
INFO : Watching for file changes with StatReloader
WARNING : Not Found: /static/admin/css/fonts.css
WARNING : Not Found: /static/admin/fonts/Roboto-Regular-webfont.woff
WARNING : Not Found: /static/admin/fonts/Roboto-Light-webfont.woff
INFO : Watching for file changes with StatReloader
WARNING : Not Found: /static/admin/img/icon-changelink.svg
WARNING : Not Found: /static/admin/img/icon-addlink.svg
WARNING : Not Found: /static/admin/js/vendor/jquery/jquery.min.js
WARNING : Not Found: /static/admin/js/vendor/xregexp/xregexp.min.js
WARNING : Not Found: /static/admin/js/vendor/jquery/jquery.min.js
WARNING : Not Found: /static/admin/js/vendor/xregexp/xregexp.min.js
WARNING : Not Found: /static/admin/img/tooltag-add.svg
WARNING : Not Found: /static/admin/js/vendor/jquery/jquery.min.js
WARNING : Not Found: /static/admin/js/vendor/xregexp/xregexp.min.js
WARNING : Not Found: /static/admin/js/vendor/jquery/jquery.min.js
WARNING : Not Found: /static/admin/js/vendor/xregexp/xregexp.min.js
WARNING : Not Found: /static/admin/js/vendor/jquery/jquery.min.js
WARNING : Not Found: /static/admin/js/vendor/xregexp/xregexp.min.js
WARNING : Not Found: /static/admin/js/vendor/jquery/jquery.min.js
WARNING : Not Found: /static/admin/js/vendor/xregexp/xregexp.min.js
WARNING : Not Found: /static/admin/img/icon-yes.svg
ERROR : Internal Server Error: /products/add_to_cart
Traceback (most recent call last):
  File "/home/amin/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/projects/github/amcsui/amcsui/products/views.py", line 13, in add_to_cart
    raise NotImplementedError
NotImplementedError
INFO : Watching for file changes with StatReloader
WARNING : Not Found: /
ERROR : Internal Server Error: /products/add_to_cart
Traceback (most recent call last):
  File "/home/amin/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/projects/github/amcsui/amcsui/products/views.py", line 17, in add_to_cart
    user = profile_finder(request)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/projects/github/amcsui/amcsui/helpers.py", line 11, in profile_finder
    profile = UserProfile.objects.get(user=user)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
users.models.UserProfile.DoesNotExist: UserProfile matching query does not exist.
INFO : /home/amin/projects/github/amcsui/amcsui/products/views.py changed, reloading.
INFO : Watching for file changes with StatReloader
ERROR : Internal Server Error: /products/add_to_cart
Traceback (most recent call last):
  File "/home/amin/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/projects/github/amcsui/amcsui/products/views.py", line 17, in add_to_cart
    user = profile_finder(request)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/projects/github/amcsui/amcsui/helpers.py", line 11, in profile_finder
    profile = UserProfile.objects.get(user=user)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
users.models.UserProfile.DoesNotExist: UserProfile matching query does not exist.
ERROR : Internal Server Error: /products/add_to_cart
Traceback (most recent call last):
  File "/home/amin/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/projects/github/amcsui/amcsui/products/views.py", line 17, in add_to_cart
    user = profile_finder(request)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/projects/github/amcsui/amcsui/helpers.py", line 11, in profile_finder
    profile = UserProfile.objects.get(user=user)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
users.models.UserProfile.DoesNotExist: UserProfile matching query does not exist.
ERROR : Internal Server Error: /products/add_to_cart
Traceback (most recent call last):
  File "/home/amin/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/projects/github/amcsui/amcsui/products/views.py", line 17, in add_to_cart
    user = profile_finder(request)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/projects/github/amcsui/amcsui/helpers.py", line 11, in profile_finder
    profile = UserProfile.objects.get(user=user)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
users.models.UserProfile.DoesNotExist: UserProfile matching query does not exist.
INFO : /home/amin/projects/github/amcsui/amcsui/amcsui/settings.py changed, reloading.
INFO : Watching for file changes with StatReloader
ERROR : Internal Server Error: /products/add_to_cart
Traceback (most recent call last):
  File "/home/amin/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/projects/github/amcsui/amcsui/products/views.py", line 17, in add_to_cart
    user = profile_finder(request)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/projects/github/amcsui/amcsui/helpers.py", line 11, in profile_finder
    profile = UserProfile.objects.get(user=user)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
users.models.UserProfile.DoesNotExist: UserProfile matching query does not exist.
INFO : /home/amin/projects/github/amcsui/amcsui/helpers.py changed, reloading.
INFO : Watching for file changes with StatReloader
INFO : /home/amin/projects/github/amcsui/amcsui/helpers.py changed, reloading.
INFO : Watching for file changes with StatReloader
ERROR : Internal Server Error: /products/add_to_cart
Traceback (most recent call last):
  File "/home/amin/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/projects/github/amcsui/amcsui/products/views.py", line 17, in add_to_cart
    user = profile_finder(request)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/projects/github/amcsui/amcsui/helpers.py", line 11, in profile_finder
    profile = UserProfile.objects.get(user=user)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
users.models.UserProfile.DoesNotExist: UserProfile matching query does not exist.
ERROR : Internal Server Error: /users/
Traceback (most recent call last):
  File "/home/amin/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/projects/github/amcsui/amcsui/users/views.py", line 16, in index
    return index_view(request)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/amin/projects/github/amcsui/amcsui/users/helpers.py", line 19, in index_view
    profile = profile_finder(request)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/projects/github/amcsui/amcsui/helpers.py", line 11, in profile_finder
    profile = UserProfile.objects.get(user=user)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
users.models.UserProfile.DoesNotExist: UserProfile matching query does not exist.
DEBUG : Invalid username or password
DEBUG : Invalid username or password
ERROR : Internal Server Error: /users/
Traceback (most recent call last):
  File "/home/amin/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/projects/github/amcsui/amcsui/users/views.py", line 16, in index
    return index_view(request)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/amin/projects/github/amcsui/amcsui/users/helpers.py", line 19, in index_view
    profile = profile_finder(request)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/projects/github/amcsui/amcsui/helpers.py", line 11, in profile_finder
    profile = UserProfile.objects.get(user=user)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
users.models.UserProfile.DoesNotExist: UserProfile matching query does not exist.
DEBUG : not loged in
DEBUG : Invalid username or password
ERROR : Internal Server Error: /products/add_to_cart
Traceback (most recent call last):
  File "/home/amin/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: users_userprofile_cart

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/amin/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/projects/github/amcsui/amcsui/products/views.py", line 20, in add_to_cart
    user.cart.add(product)
  File "/home/amin/.local/lib/python3.11/site-packages/django/db/models/fields/related_descriptors.py", line 1087, in add
    self._add_items(
  File "/home/amin/.local/lib/python3.11/site-packages/django/db/models/fields/related_descriptors.py", line 1329, in _add_items
    self.through._default_manager.using(db).bulk_create(
  File "/home/amin/.local/lib/python3.11/site-packages/django/db/models/query.py", line 816, in bulk_create
    returned_columns = self._batched_insert(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/db/models/query.py", line 1825, in _batched_insert
    self._insert(
  File "/home/amin/.local/lib/python3.11/site-packages/django/db/models/query.py", line 1791, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1660, in execute_sql
    cursor.execute(sql, params)
  File "/home/amin/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/home/amin/.local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/amin/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: users_userprofile_cart
INFO : Watching for file changes with StatReloader
WARNING : Not Found: /
INFO : /home/amin/projects/github/amcsui/amcsui/users/models.py changed, reloading.
INFO : Watching for file changes with StatReloader
INFO : /home/amin/projects/github/amcsui/amcsui/products/views.py changed, reloading.
INFO : Watching for file changes with StatReloader
WARNING : Not Found: /ad/
ERROR : Internal Server Error: /products/add_to_cart
Traceback (most recent call last):
  File "/home/amin/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/projects/github/amcsui/amcsui/products/views.py", line 22, in add_to_cart
    return HttpResponseRedirect(reverse("products:_view"))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for '_view' with no arguments not found. 1 pattern(s) tried: ['products/(?P<name>[^/]+)\\Z']
INFO : /home/amin/projects/github/amcsui/amcsui/products/views.py changed, reloading.
INFO : Watching for file changes with StatReloader
INFO : /home/amin/projects/github/amcsui/amcsui/products/views.py changed, reloading.
INFO : Watching for file changes with StatReloader
ERROR : Internal Server Error: /products/add_to_cart
Traceback (most recent call last):
  File "/home/amin/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/projects/github/amcsui/amcsui/products/views.py", line 22, in add_to_cart
    return HttpResponseRedirect(request.HTTP_REFERER)
                                ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'WSGIRequest' object has no attribute 'HTTP_REFERER'
INFO : /home/amin/projects/github/amcsui/amcsui/products/views.py changed, reloading.
INFO : Watching for file changes with StatReloader
ERROR : Internal Server Error: /products/add_to_cart
Traceback (most recent call last):
  File "/home/amin/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/projects/github/amcsui/amcsui/products/views.py", line 22, in add_to_cart
    return HttpResponseRedirect(request.url)
                                ^^^^^^^^^^^
AttributeError: 'WSGIRequest' object has no attribute 'url'
ERROR : Internal Server Error: /products/add_to_cart
Traceback (most recent call last):
  File "/home/amin/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/projects/github/amcsui/amcsui/products/views.py", line 22, in add_to_cart
    return HttpResponseRedirect(request.url)
                                ^^^^^^^^^^^
AttributeError: 'WSGIRequest' object has no attribute 'url'
INFO : /home/amin/projects/github/amcsui/amcsui/products/views.py changed, reloading.
INFO : Watching for file changes with StatReloader
INFO : Watching for file changes with StatReloader
WARNING : Not Found: /
DEBUG : not loged in
DEBUG : Invalid username or password
DEBUG : Invalid username or password
ERROR : Internal Server Error: /flights/bookaflight/
Traceback (most recent call last):
  File "/home/amin/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/projects/github/amcsui/amcsui/flights/views.py", line 21, in book
    return book_view(request)
           ^^^^^^^^^^^^^^^^^^
  File "/home/amin/projects/github/amcsui/amcsui/flights/helpers.py", line 15, in book_view
    if flight.is_bookable(user_profile):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/projects/github/amcsui/amcsui/flights/models.py", line 27, in is_bookable
    return (self.capacity > self.passengers) and (self.cost < user.credit)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '>' not supported between instances of 'int' and 'ManyRelatedManager'
ERROR : Internal Server Error: /flights/bookaflight/
Traceback (most recent call last):
  File "/home/amin/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/projects/github/amcsui/amcsui/flights/views.py", line 21, in book
    return book_view(request)
           ^^^^^^^^^^^^^^^^^^
  File "/home/amin/projects/github/amcsui/amcsui/flights/helpers.py", line 15, in book_view
    if flight.is_bookable(user_profile):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/projects/github/amcsui/amcsui/flights/models.py", line 27, in is_bookable
    return (self.capacity > self.passengers) and (self.cost < user.credit)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '>' not supported between instances of 'int' and 'ManyRelatedManager'
DEBUG : not loged in
DEBUG : not loged in
INFO : Watching for file changes with StatReloader
ERROR : Internal Server Error: /flights/bookaflight/
Traceback (most recent call last):
  File "/home/amin/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/projects/github/amcsui/amcsui/flights/views.py", line 21, in book
    return book_view(request)
           ^^^^^^^^^^^^^^^^^^
  File "/home/amin/projects/github/amcsui/amcsui/flights/helpers.py", line 15, in book_view
    if flight.is_bookable(user_profile):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amin/projects/github/amcsui/amcsui/flights/models.py", line 28, in is_bookable
    return (self.capacity > len(self.passengers)) and (self.cost < user.credit)
                            ^^^^^^^^^^^^^^^^^^^^
TypeError: object of type 'ManyRelatedManager' has no len()
DEBUG : Using selector: EpollSelector
DEBUG : Using selector: EpollSelector
DEBUG : diff parser start
DEBUG : line_lengths old: 1; new: 1
DEBUG : -> code[replace] old[1:1] new[1:1]
DEBUG : parse_part from 1 to 1 (to 0 in part parser)
DEBUG : diff parser end
DEBUG : pickle loaded: /home/amin/.local/lib/python3.11/site-packages/jedi/third_party/typeshed/stdlib/3/builtins.pyi
DEBUG : pickle loaded: /home/amin/.local/lib/python3.11/site-packages/jedi/third_party/typeshed/stdlib/3/sys.pyi
DEBUG : diff parser start
DEBUG : line_lengths old: 1; new: 1
DEBUG : -> code[replace] old[1:1] new[1:1]
DEBUG : parse_part from 1 to 1 (to 0 in part parser)
DEBUG : diff parser end
DEBUG : diff parser start
DEBUG : line_lengths old: 1; new: 1
DEBUG : -> code[replace] old[1:1] new[1:1]
DEBUG : parse_part from 1 to 1 (to 0 in part parser)
DEBUG : diff parser end
DEBUG : pickle loaded: /home/amin/.local/lib/python3.11/site-packages/django/__init__.py
DEBUG : pickle loaded: /home/amin/.local/lib/python3.11/site-packages/jedi/third_party/django-stubs/django-stubs/__init__.pyi
DEBUG : diff parser start
DEBUG : line_lengths old: 1; new: 1
DEBUG : -> code[replace] old[1:1] new[1:1]
DEBUG : parse_part from 1 to 1 (to 0 in part parser)
DEBUG : diff parser end
DEBUG : diff parser start
DEBUG : line_lengths old: 1; new: 1
DEBUG : -> code[replace] old[1:1] new[1:1]
DEBUG : parse_part from 1 to 1 (to 0 in part parser)
DEBUG : diff parser end
INFO : Watching for file changes with StatReloader
